"""
Django settings for afri_cleans project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment: used to drive security-sensitive defaults
ENVIRONMENT = os.environ.get("ENVIRONMENT", "development").lower()

# Load environment variables from a local .env file (for development).
# In production we avoid loading .env implicitly to prevent fallback secrets.
if ENVIRONMENT != "production":
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Must be provided via environment (for local dev, via .env).
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is controlled by environment; if not explicitly set, it is OFF in production.
DEBUG = os.environ.get(
    'DEBUG',
    'False' if ENVIRONMENT == 'production' else 'True',
).lower() == 'true'

allowed_hosts_env = os.environ.get('ALLOWED_HOSTS')
if allowed_hosts_env is None and ENVIRONMENT != 'production':
    allowed_hosts_env = 'localhost,127.0.0.1'

ALLOWED_HOSTS = [h.strip() for h in (allowed_hosts_env or '').split(',') if h.strip()]

# For security, never allow wildcard hosts in production
if ENVIRONMENT == 'production' and '*' in os.environ.get('ALLOWED_HOSTS', ''):
    raise ValueError("Wildcard ALLOWED_HOSTS is not permitted in production")
if ENVIRONMENT == 'production' and not ALLOWED_HOSTS:
    raise ValueError("ALLOWED_HOSTS must be set in production")
if ENVIRONMENT == 'production' and DEBUG:
    raise ValueError("DEBUG must be False in production")

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]


# Default primary key for models without explicit PK (avoids Django 3.2+ warnings)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'afri_cleans.middleware.ApiJsonExceptionMiddleware',
]

ROOT_URLCONF = 'afri_cleans.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'afri_cleans.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# CORS Settings
# Configure allowed origins via CORS_ALLOWED_ORIGINS env var
# e.g. CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if o.strip()
]

CORS_ALLOW_CREDENTIALS = True

# Production security (HTTPS, cookies, HSTS). Tune via environment when behind a reverse proxy.
if ENVIRONMENT == 'production':
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
    CSRF_COOKIE_HTTPONLY = os.environ.get('CSRF_COOKIE_HTTPONLY', 'False').lower() == 'true'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
    SECURE_CROSS_ORIGIN_OPENER_POLICY = os.environ.get(
        'SECURE_CROSS_ORIGIN_OPENER_POLICY',
        'same-origin',
    )
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True'
    ).lower() == 'true'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    if os.environ.get('TRUST_X_FORWARDED_PROTO', '').lower() == 'true':
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# REST Framework Settings
REST_FRAMEWORK = {
    # Default to authenticated-only API; public endpoints must explicitly override
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    # Consistent JSON error responses for API endpoints
    'EXCEPTION_HANDLER': 'afri_cleans.api_errors.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('DRF_THROTTLE_ANON', '120/hour'),
        'user': os.environ.get('DRF_THROTTLE_USER', '500/hour'),
        'booking_create': os.environ.get('DRF_THROTTLE_BOOKING_CREATE', '6/hour'),
        'contact_create': os.environ.get('DRF_THROTTLE_CONTACT_CREATE', '5/hour'),
    },
}

# Optional anti-bot captcha validation for public POST forms (Google reCAPTCHA siteverify).
# In production, CONTACT_FORM_CAPTCHA_SECRET is required unless you explicitly opt out
# (see ALLOW_PUBLIC_FORMS_WITHOUT_CAPTCHA) — empty secret means no captcha in non-production only.
CONTACT_FORM_CAPTCHA_SECRET = os.environ.get('CONTACT_FORM_CAPTCHA_SECRET', '').strip()
# Explicit opt-out for production when captcha is not wired yet (not recommended long-term).
ALLOW_PUBLIC_FORMS_WITHOUT_CAPTCHA = os.environ.get(
    'ALLOW_PUBLIC_FORMS_WITHOUT_CAPTCHA', 'False'
).lower() == 'true'
# reCAPTCHA v3: minimum score (0.0–1.0). If unset, 0.5 is used when Google returns a score.
_recaptcha_min_raw = os.environ.get('RECAPTCHA_MIN_SCORE', '').strip()
RECAPTCHA_MIN_SCORE = float(_recaptcha_min_raw) if _recaptcha_min_raw else None
# Optional: hostname must match siteverify response (defense in depth).
RECAPTCHA_EXPECTED_HOSTNAME = os.environ.get('RECAPTCHA_EXPECTED_HOSTNAME', '').strip()

if ENVIRONMENT == 'production':
    if not CONTACT_FORM_CAPTCHA_SECRET and not ALLOW_PUBLIC_FORMS_WITHOUT_CAPTCHA:
        raise ImproperlyConfigured(
            'Production requires CONTACT_FORM_CAPTCHA_SECRET for public booking/contact '
            'forms, or set ALLOW_PUBLIC_FORMS_WITHOUT_CAPTCHA=true to acknowledge captcha '
            'is disabled (not recommended).'
        )

# Email Settings
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',  # sensible default for dev
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@example.com')

# Optional SMTP configuration for non-console backends
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# VAT/Tax Configuration
def _get_decimal_rate(env_key: str, default: str) -> float:
    """Parse decimal rate from env and enforce 0..1 inclusive bounds."""
    raw_value = os.environ.get(env_key, default)
    try:
        parsed = float(raw_value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{env_key} must be a decimal number between 0 and 1") from exc
    if parsed < 0 or parsed > 1:
        raise ValueError(f"{env_key} must be between 0 and 1")
    return parsed


DEFAULT_VAT_RATE = _get_decimal_rate('DEFAULT_VAT_RATE', '0.20')  # UK standard VAT default
APPLY_VAT_BY_DEFAULT = os.environ.get('APPLY_VAT_BY_DEFAULT', 'True').lower() == 'true'

# Logging configuration
# Avoid logging request bodies or sensitive fields; send structured logs to stdout
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "format": '{"level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}',
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        # Keep Django request logs but avoid including full request bodies
        "django.request": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # Application-level logging (e.g. core.views)
        "core": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
