# Generated by Django 6.0.3 on 2026-03-05 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billing_type',
            field=models.CharField(choices=[('fixed', 'Fixed package'), ('hourly', 'Hourly billing')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours for the job (used for hourly billing).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated quote calculated for this booking.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='job_type',
            field=models.CharField(choices=[('residential', 'Residential Cleaning'), ('commercial', 'Commercial Cleaning'), ('office', 'Office Cleaning'), ('hourly', 'Per-Hour Cleaning')], default='residential', max_length=20),
        ),
    ]
