# Generated by Django 6.0.3 on 2026-03-06 08:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_billing_type_booking_estimated_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('badge_text', models.CharField(blank=True, help_text="Short badge text like 'Limited Time'", max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 15.00 for 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('promo_code', models.CharField(help_text='Unique promotional code', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Promotional code applied to this booking.', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage applied from promotion.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal before tax/VAT.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount including VAT.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT amount calculated.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='Service description and line items')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.booking')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
